### ISSUE TITLE
Remove dependency to s3signed

### ISSUE THREAD

**Issue by mitjap** [mapbox/s3urls#11]
`s3signed` has it's own dependencies with and these have their own. It's really unnecessary  since all you do with this dependency is to export it.

**Comment by mitjap** [comment]
Very nice view of dependency tree for `s3urls`
http://npm.anvaka.com/#/view/2d/s3urls

**Comment by ingalls** [comment]
@mitjap The s3signed dependency is used here: https://github.com/mapbox/s3urls/blob/master/bin/s3urls.js#L59-L68
